In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[10,11,12],[13,14,15]])

print(np.add(arr1, arr2))

[[11 13 15]
 [17 19 21]]


In [3]:
arr = np.array([[1,2,3],[4,5,6]])
print(np.multiply(arr,2))

[[ 2  4  6]
 [ 8 10 12]]


In [4]:
print(np.identity(4, dtype=int))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [5]:
arr1D = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,25])
print(arr1D.reshape(3,3,3))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 25]]]


In [6]:
originalArr = np.array([[2.5,3.8,1.5],[4.7,2.9,1.56]])
print('original array:', originalArr)

intArr = originalArr.astype(int)
print('integer datatype array:', intArr)

original array: [[2.5  3.8  1.5 ]
 [4.7  2.9  1.56]]
integer datatype array: [[2 3 1]
 [4 2 1]]


In [7]:
binArr = np.array([[1,0,0],[1,1,1],[0,0,0]])
print('original:', binArr)

boolArr = binArr.astype(bool)
print('bool array:', boolArr)

original: [[1 0 0]
 [1 1 1]
 [0 0 0]]
bool array: [[ True False False]
 [ True  True  True]
 [False False False]]


In [8]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

print(np.hstack((arr1,arr2)))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [9]:
rangeArr = np.arange(0,101,2)
print(rangeArr)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [10]:
randArr = np.random.rand(1000000)

sum = 0
for i in randArr:
    sum += i

print(sum)

500189.05831394525


In [11]:
print(np.sum(randArr))

500189.0583139245


In [12]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,3,2,4,5])

result = np.where(arr1 == arr2)
print(result)

(array([0, 3, 4]),)


In [13]:
print(np.linspace(0,100,num=5))

[  0.  25.  50.  75. 100.]


In [14]:
print(np.full((2,3),5))

[[5 5 5]
 [5 5 5]]


In [15]:
print(np.random.randint(0,11,(5,5)))

[[ 5  3  1  4  1]
 [ 9  5  8  7  8]
 [10  7  9  1  8]
 [ 6  6  7  0  0]
 [ 0  1  7  3  6]]


In [16]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[2,3,4],[5,6,7],[8,9,10]])

print(np.dot(arr1,arr2))

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


In [17]:
arr = np.random.random((2,3))
print('original',arr)

print('transpose', arr.T)

original [[0.52822261 0.35226806 0.21469589]
 [0.10439322 0.36162205 0.9484677 ]]
transpose [[0.52822261 0.10439322]
 [0.35226806 0.36162205]
 [0.21469589 0.9484677 ]]


In [18]:
arr = np.array([[2,2,2,2,2],[15,6,27,8,2],[23,2,54,1,2],[11,44,34,7,2]])

# for flatten
print('flatten', np.std(arr))

#for axis 0 and 1
print('axis 0', np.std(arr,axis=0)) #axis 0
print('axis 1', np.std(arr,axis=1)) # axis 1

flatten 15.3668474320532
axis 0 [ 7.56224173 17.68473918 18.59267329  3.04138127  0.        ]
axis 1 [ 0.          8.7772433  20.53874388 16.40243884]


In [19]:
arr = np.array([[6,1,1],[4,-2,5],[2,8,7]])

print(np.linalg.inv(arr))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [20]:
!pip install pillow

In [22]:
from PIL import Image
import numpy as np  # <-- Missing import

img = Image.open("free-nature-images.jpg")

picArr = np.array(img)

print(picArr)
print(picArr.shape)
print(picArr.dtype)


FileNotFoundError: [Errno 2] No such file or directory: 'free-nature-images.jpg'

In [23]:
demoDict = {0: 0, 1: 1, 2: 8, 3: 27, 4: 64, 5: 125, 6: 216}

arr = np.array(list(demoDict.items()))
print(arr)

[[  0   0]
 [  1   1]
 [  2   8]
 [  3  27]
 [  4  64]
 [  5 125]
 [  6 216]]


In [24]:
x = np.array([[3,1,-2],[2,-1,1],[1,2,3]])
b = np.array([9,3,12])

print(np.linalg.solve(x,b))

[2.6 3.2 1. ]


In [25]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(arr.shape)
print(arr)

(3, 3, 3)
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [26]:
print(arr.reshape(-1,))

[1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7 8 9]


In [27]:
arr = np.random.rand(3, 3)
print("Array:\n", arr)

#euclidian distance = distance between every pair of rows.

dist_matrix = np.zeros((3, 3))
for i in range(3):
    for j in range(3):
        #norm = distance between two given vectors.
        dist_matrix[i, j] = np.linalg.norm(arr[i] - arr[j])

print("\nPairwise Distance Matrix:\n", dist_matrix)

Array:
 [[0.78368028 0.65016107 0.03936709]
 [0.63663409 0.45342623 0.54456543]
 [0.84936023 0.56874699 0.56578698]]

Pairwise Distance Matrix:
 [[0.         0.56174064 0.53671223]
 [0.56174064 0.         0.24290254]
 [0.53671223 0.24290254 0.        ]]
